# Generated by Django 6.0.1 on 2026-01-27 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_profilepicture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfilePicture',
        ),
    ]
