# Generated by Django 6.0.1 on 2026-01-27 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_delete_profilepicture'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sketch', models.ImageField(upload_to='images/')),
                ('original', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
