# Generated by Django 6.0.1 on 2026-01-27 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_profilepicture'),
    ]

    operations = [
        migrations.CreateModel(
            name='WelcomeNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('line1', models.TextField()),
                ('line2', models.TextField()),
            ],
        ),
    ]
