# Generated by Django 6.0.1 on 2026-01-27 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_welcomenote'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoreList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(max_length=50)),
            ],
        ),
    ]
