# Generated by Django 6.0.1 on 2026-01-27 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_morelist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MoreList',
        ),
    ]
