# Generated by Django 6.0.1 on 2026-01-27 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_experience'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Education',
        ),
    ]
