# Generated by Django 6.0.1 on 2026-01-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_delete_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instiitute', models.CharField(max_length=150)),
                ('degree', models.CharField(max_length=150)),
                ('description', models.TextField()),
            ],
        ),
    ]
