# Generated by Django 6.0.1 on 2026-01-27 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_education'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
