# Generated by Django 6.0.1 on 2026-01-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_delete_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameForPercentage', models.CharField(max_length=100)),
                ('percentage', models.IntegerField()),
                ('nameForLearned', models.CharField(max_length=50)),
                ('svg', models.URLField()),
            ],
        ),
    ]
